server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/htmlcssdatabase
spring.datasource.username=postgres
spring.datasource.password=2402

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.application.name=htmlcssgenerator